services:
  - type: web
    name: bd-finance-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm run build
    startCommand: npx http-server dist/bd-finance/browser -p $PORT
    publishDirectory: dist/bd-finance/browser
    envVars:
      - key: API_BASE_URL
        value: https://bd-finance-backend.onrender.com/api
